### ISSUE TITLE
Custom shortcode overriding Hugo's new built-in shortcode

### ISSUE THREAD

**Issue by wooseopkim** [panr/hugo-theme-terminal#118]
`figure.html` overrides Hugo's <https://gohugo.io/content-management/shortcodes/#figure>.

Its source code is at <https://github.com/gohugoio/hugo/blob/aba2647c152ffff927f42523b77ee6651630cd67/tpl/tplimpl/embedded/templates/shortcodes/figure.html>.

IMO we should either namespace or remove this theme's `figure` shortcode.

**Comment by wooseopkim** [comment]
@panr Since you replied to #121 but not to this, as a gentle alert, could you take a look at this issue?

**Comment by panr** [comment]
What's wrong with my implementation? Do you miss something from the original shortcode? Please let me know 👍

**Comment by wooseopkim** [comment]
The problem is that now Hugo provides its own `figure` shortcode, which is a little bit different from this theme's `figure`. And `terminal` theme's one overrides the new Hugo one.

**Comment by panr** [comment]
I get it, but if there's something missing or working differently in your case? We can merge the code of those two and provide the `uber-figure` (not the actual name, hehe) shortcode. What do you think?

**Comment by wooseopkim** [comment]
I've had some trouble figuring out why #121 happened to me, more or less because of this. Also transitions (from other themes into `terminal` theme) would be easier, because `figure` might get broken if a post is written assuming Hugo's `figure`. Your solution, merging into a new one, looks nice to me.

**Comment by n00bmind** [comment]
Coming here a few months too late to say that yes, the custom figure override in this theme is missing quite a few of the functionalities of the currently built-in one, just as a way of example, all my figures with links stopped working once I installed this theme and it took me quite a while to figure out what the reason was.

I'm right now forced to simply delete figure.html from this theme if I want to keep using it. Not good.
