### ISSUE TITLE
How can i get the source code of the sample website?

### ISSUE THREAD

**Issue by theloganlab** [panr/hugo-theme-terminal#344]
The demo website in https://hugo-terminal.vercel.app? i have a lot of questions about the drop down menus and more things that will be solve if i see how did you do it in the sample one

**Comment by pierre-manchon** [comment]
I think that what you're searching for is in [assets](https://github.com/panr/hugo-theme-terminal/tree/master/assets) and in [layouts](https://github.com/panr/hugo-theme-terminal/tree/master/assets).
Otherwise for the 'sample' specifically, i think inspecting the web page and its css/js files would be enough

**Comment by RafaelMoreira1180778** [comment]
> Where is this welcome blurb being configured? ![image](https://user-images.githubusercontent.com/11330843/175823586-2e23093b-a3cb-4b63-88db-186f78574cdc.png)

Also looking for this as well.

**Comment by reavessm** [comment]
I think you are looking for [this](https://github.com/panr/hugo-theme-terminal/issues/187#issuecomment-682464306)

**Comment by RafaelMoreira1180778** [comment]
> I think you are looking for [this](https://github.com/panr/hugo-theme-terminal/issues/187#issuecomment-682464306)

Exactly, thank you very much!
