### ISSUE TITLE
Feature request: Light theme and Switcher

### ISSUE THREAD

**Issue by ariestiyansyah** [panr/hugo-theme-terminal#46]
Add feature to switch dark and light mode like hello-friend theme will be good

**Comment by rampadc** [comment]
I recently made a light theme variant. I didn't make a PR though since there are two destructive changes, namely border colours for the blog post and the code block. Still working through making them non-destructive.

If you want to have a go at creating a custom variant, I wrote the process up at https://congx.dev/posts/custom-light-terminal-theme
