### ISSUE TITLE
Feature request: Add anchors to headers

### ISSUE THREAD

**Issue by roobre** [panr/hugo-theme-terminal#87]
Hi,

Thanks for the great work, I'm loving your theme for my (poorly updated) blog <3

I'd like to ask if you're considering anchorized headers in your roadmap. I think they are quite useful when you have a big post and want to link someone to an specific section. Should be easy to implement, at least the technical part, specially given that hugo already provide useful primitives (like [anchorize](https://gohugo.io/functions/anchorize/)).

The visual part is maybe a bit trickier, perhaps something like what github does for markdown (showing a :link: icon when you hover the header) is the fanciest and won't disrupt header links, but may be more painful to implement.

What are your thoughts on this? If you think it'd be a great addition maybe I can work on a PR.

Regards!

**Comment by sophiabrandt** [comment]
Hello @roobre .
The anchored links already work, you can append them to your website link with #h1-title.
For example:
https://hugo-terminal.now.sh/post/hugoisforlovers/#step-2-build-the-docs

At the moment, you have to manually construct the #hash part of the link (replace whitespace with hyphens, all lowercase), but it works.

A visual representation would be nice though...

**Comment by roobre** [comment]
Hi,
Thank you for this!

As a first approach for the visual representation/link obtaining, what about just wrapping the headers in `<a href="#generated-anchor>`? This should be easy to do using exactly the same method used to generate the header `id`s.

**Comment by sophiabrandt** [comment]
I'm not @panr, but I googled around a bit and found a solution.

1. Here's how you can configure the Markdown parser:
https://gohugo.io/getting-started/configuration-markup
The standard parser from 0.60 is Goldmark and it automatically creates links and anchor headers: https://gohugo.io/content-management/cross-references/#hugo-heading-anchors
That's why manually creating a "hash link" works.
The `config.toml` is in your project, so there's no need to change the theme.

2. For the little anchor svg (or something similar) you either need JavaScript, or you can use some inbuild hugo features. For that, you'll need to adjust the theme.
https://discourse.gohugo.io/t/adding-anchor-next-to-headers/1726/13
I will try to create a pull request for this feature.
